/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Graphics;

/**
 *
 * @author Madawa
 */
public class ScoreBoard extends javax.swing.JPanel {

    /**
     * Creates new form Scores
     */
    public ScoreBoard() {
        initComponents();
    }
    
    public static void updateScores(int[][] scores, int size) {
        for(int i = 0; i < size; ++i){
            switch(scores[i][0]){
                default:
                    break;
                case 0:
                    scoreP0.setText(Integer.toString(scores[i][1]));
                    healthP0.setText(Integer.toString(scores[i][2]));
                    break;
                case 1:
                    scoreP1.setText(Integer.toString(scores[i][1]));
                    healthP1.setText(Integer.toString(scores[i][2]));
                    break;
                case 2:
                    scoreP2.setText(Integer.toString(scores[i][1]));
                    healthP2.setText(Integer.toString(scores[i][2]));
                    break;
                case 3:
                    scoreP3.setText(Integer.toString(scores[i][1]));
                    healthP3.setText(Integer.toString(scores[i][2]));
                    break;
                case 4:
                    scoreP4.setText(Integer.toString(scores[i][1]));
                    healthP4.setText(Integer.toString(scores[i][2]));
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconP0 = new javax.swing.JLabel();
        iconP1 = new javax.swing.JLabel();
        iconP2 = new javax.swing.JLabel();
        iconP3 = new javax.swing.JLabel();
        iconP4 = new javax.swing.JLabel();
        scoreP3 = new javax.swing.JLabel();
        healthP4 = new javax.swing.JLabel();
        healthP3 = new javax.swing.JLabel();
        scoreP4 = new javax.swing.JLabel();
        scoreP2 = new javax.swing.JLabel();
        healthP2 = new javax.swing.JLabel();
        scoreP1 = new javax.swing.JLabel();
        healthP1 = new javax.swing.JLabel();
        healthP0 = new javax.swing.JLabel();
        scoreP0 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 248, 181));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(424, 302));
        setName("Score Board"); // NOI18N
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconP0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tank2.png"))); // NOI18N
        add(iconP0, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 101, -1, -1));

        iconP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tank2.png"))); // NOI18N
        add(iconP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 58, -1, -1));

        iconP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tank2.png"))); // NOI18N
        iconP2.setToolTipText("");
        add(iconP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 187, -1, -1));

        iconP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tank2.png"))); // NOI18N
        add(iconP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 144, -1, -1));

        iconP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tank2.png"))); // NOI18N
        iconP4.setToolTipText("");
        add(iconP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 230, -1, -1));

        scoreP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scoreP3.setForeground(new java.awt.Color(0, 0, 255));
        scoreP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreP3.setText("0000");
        scoreP3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(scoreP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 187, 108, 25));

        healthP4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        healthP4.setForeground(new java.awt.Color(0, 0, 255));
        healthP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthP4.setText("0000");
        healthP4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(healthP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 230, 108, 25));

        healthP3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        healthP3.setForeground(new java.awt.Color(0, 0, 255));
        healthP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthP3.setText("0000");
        healthP3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(healthP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 187, 108, 25));

        scoreP4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scoreP4.setForeground(new java.awt.Color(0, 0, 255));
        scoreP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreP4.setText("0000");
        scoreP4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(scoreP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 230, 108, 25));

        scoreP2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scoreP2.setForeground(new java.awt.Color(0, 0, 255));
        scoreP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreP2.setText("0000");
        scoreP2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(scoreP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 144, 108, 25));

        healthP2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        healthP2.setForeground(new java.awt.Color(0, 0, 255));
        healthP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthP2.setText("0000");
        healthP2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(healthP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 144, 108, 25));

        scoreP1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scoreP1.setForeground(new java.awt.Color(0, 0, 255));
        scoreP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreP1.setText("0000");
        scoreP1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(scoreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 101, 108, 25));

        healthP1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        healthP1.setForeground(new java.awt.Color(0, 0, 255));
        healthP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthP1.setText("0000");
        healthP1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(healthP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 101, 108, 25));

        healthP0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        healthP0.setForeground(new java.awt.Color(0, 0, 255));
        healthP0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthP0.setText("0000");
        healthP0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(healthP0, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 58, 108, 25));

        scoreP0.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        scoreP0.setForeground(new java.awt.Color(0, 0, 255));
        scoreP0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreP0.setText("0000");
        scoreP0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(scoreP0, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 58, 108, 25));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel healthP0;
    private static javax.swing.JLabel healthP1;
    private static javax.swing.JLabel healthP2;
    private static javax.swing.JLabel healthP3;
    private static javax.swing.JLabel healthP4;
    private javax.swing.JLabel iconP0;
    private javax.swing.JLabel iconP1;
    private javax.swing.JLabel iconP2;
    private javax.swing.JLabel iconP3;
    private javax.swing.JLabel iconP4;
    private static javax.swing.JLabel scoreP0;
    private static javax.swing.JLabel scoreP1;
    private static javax.swing.JLabel scoreP2;
    private static javax.swing.JLabel scoreP3;
    private static javax.swing.JLabel scoreP4;
    // End of variables declaration//GEN-END:variables
}
